# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Automating Inequity: Predictive Policing, Algorithmic Bias, and the Crises of Mass Incarceration
tagline:          ''
description:      'A 2022 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://edxijiez.github.io"
baseurl:          "/soc401Final"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/edxijiez/soc401Final/
